name: App Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: alwanof
          repo: admix_QA
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: wf.yml
          wait_workflow: true