name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: keithconvictional
          repo: admix_test
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: node.js.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s